Mypy: evaluateclassifier is both imported and defined
$ `mypy --ignore-missing-imports .
```
pyAudioProcessing/trainer/audioTrainTest.py:65: error: Name 'evaluateclassifier' already defined (possibly by an import)
Found 1 error in 1 file (checked 11 source files)
```
http://mypy-lang.org